# Generated by Django 4.2.3 on 2023-08-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('t-shirts', 'T-Shirts'), ('jackets', 'Jackets'), ('jeans', 'Jeans')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
