# Generated by Django 4.2.3 on 2023-08-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=1, verbose_name='Image URL'),
            preserve_default=False,
        ),
    ]
